# Generated by Django 2.1.3 on 2018-11-08 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='group_of_products',
            field=models.ManyToManyField(blank=True, to='core.GroupOfProducts', verbose_name='Підкатегорія'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='characteristic',
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Characteristic', verbose_name='Характеристика'),
        ),
    ]
