# Generated by Django 2.1.3 on 2018-11-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181115_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupofproducts',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='groups_photo', verbose_name='Логотип групи'),
        ),
    ]
