# Generated by Django 2.1.3 on 2018-11-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181108_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristic',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='', verbose_name='Фото товару'),
        ),
    ]
