# Generated by Django 2.1.3 on 2018-11-09 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181109_1237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courier',
            options={'verbose_name': 'кур’єр', 'verbose_name_plural': 'Кур’єри'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'робітник', 'verbose_name_plural': 'Робітники'},
        ),
    ]
