# Generated by Django 2.1.3 on 2018-11-21 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_groupofproducts_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='client',
        ),
        migrations.AddField(
            model_name='basket',
            name='consumer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basket', to='core.Consumer', verbose_name='Клієнт', null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basket',
            name='position_in_the_basket',
            field=models.ManyToManyField(blank=True, to='core.PositionInTheBasket', verbose_name='Позиція в корзині'),
        ),
    ]
