# Generated by Django 2.1.3 on 2018-11-09 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181109_1359'),
        ('core', '0004_auto_20181109_1335'),
    ]

    operations = [
    ]
